### ISSUE TITLE
Build the maven example in the build

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-emf-parsley/emf-parsley#43]

**Comment by LorenzoBettini** [comment]
Current problem in the reactor:

```
Error:  Failed to execute goal org.eclipse.xtext:xtext-maven-plugin:2.29.0:generate (default) on project org.eclipse.emf.parsley.examples.maven: Execution default of goal org.eclipse.xtext:xtext-maven-plugin:2.29.0:generate failed: Unable to create injector, see the following errors:
Error:  
Error:  1) [Guice/ErrorInjectingConstructor]: SecurityException: class "org.eclipse.jface.viewers.ITreeContentProvider"'s signer information does not match signer information of other classes in the same package
Error:    at EmfParsleyDslExpectedSuperTypes.<init>(EmfParsleyDslExpectedSuperTypes.java:61)
Error:    at EmfParsleyDslExpectedSuperTypes.class(EmfParsleyDslExpectedSuperTypes.java:59)
Error:    at EmfParsleyDslValidator._emfParsleyDslExpectedSuperTypes(EmfParsleyDslValidator.java:65)
Error:        \_ for field _emfParsleyDslExpectedSuperTypes
Error:    at MethodBasedModule.configure(MethodBasedModule.java:58)
Error:    while locating EmfParsleyDslValidator
Error:  
Error:  Learn more:
Error:    https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR
Error: [ERROR] 
Error: [ERROR] 1 error
Error:  
Error:  ======================
Error:  Full classname legend:
Error:  ======================
Error:  EmfParsleyDslExpectedSuperTypes: "org.eclipse.emf.parsley.dsl.validation.EmfParsleyDslExpectedSuperTypes"
Error:  EmfParsleyDslValidator:          "org.eclipse.emf.parsley.dsl.validation.EmfParsleyDslValidator"
Error:  MethodBasedModule:               "org.eclipse.xtext.service.MethodBasedModule"
Error:  ========================
Error:  End of classname legend:
Error:  ========================
Error:  
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :org.eclipse.emf.parsley.examples.maven
Error: Process completed with exit code 1.
```

**Comment by LorenzoBettini** [comment]
That example is meant to be used in a pure Maven build, so we should remove the Tycho stuff and make it pure Maven (probably it can be built only on a second run).

Currently, we have `org.eclipse.emf.parsley.tests.views` where we can run the xtext-maven-plugin with the standard DSL bundle (NOT standalone)
